# Generated by Django 3.2.9 on 2021-12-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('quiz2', '0003_alter_question_title'),
        ('authtoken', '0003_tokenproxy'),
        ('accounts', '0003_score_topusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopUsers',
        ),
    ]
