# Generated by Django 3.2.9 on 2021-12-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_topusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Login', max_length=25),
        ),
    ]
