# Generated by Django 3.2.9 on 2021-12-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz2', '0003_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='technique',
            field=models.IntegerField(choices=[(0, 'Multiple Choice')], default=0, verbose_name='Type of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='Topic of Questions', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Description', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='Description of the Quiz'),
        ),
    ]
