# Generated by Django 3.2.9 on 2021-12-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz2', '0004_auto_20211220_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(default='Topic of Quiz', max_length=255),
        ),
    ]
